### ISSUE TITLE
Highlight areas that are likely text

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#16]
While in the camera view, the app should highlight areas in orange if the TensorFlow model provides evidence suggesting that it is likely to be text.

**Comment by carpenterd777** [comment]
I'm not sure if this is possible anymore considering all the ML is off-device. thoughts @dyc3 ?

**Comment by dyc3** [comment]
I'm pretty sure that tesseract can give us that info, we just have to add it to the api response.

**Comment by carpenterd777** [comment]
do you think the response will come back fast enough to be done dynamically like this though? also, will heroku be able to handle such a volume of requests (1/frame) ?

**Comment by dyc3** [comment]
Ohhh, yeah no probably not feasible.

**Comment by carpenterd777** [comment]
Alright, we'll close this issue with that in mind.
