### ISSUE TITLE
Use Tesseract C++ instead of creating a custom Tensorflow model.

### ISSUE THREAD

**Issue by aejester** [StevensSEC/monocle#28]
To preface: I acknowledge that this may be more difficult than creating an actual model and integrating it using TensorFlow, but Tesseract is a very promising library. I believe, with extensive research before putting work in, that the solution weakly outlined below could be a great way to solve this issue.

Tesseract has a [C++ API](https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/baseapi.h) which we can use in React Native because of its way to use C++ through Objective-C and Java bindings.

To create these bindings we will have to use a tool called [djinni](https://github.com/dropbox/djinni) which is maintained by dropbox. This tool has the ability to create Objective-C and Java bindings (provided we create the C++ wrapper for what we are using). I don't believe we need to eject for this...however, at the time of writing this, it is 11:02 PM and I am tired and sad because of countless dead ends. I did not look too deep into how to use djinni, but I do know that the Tesseract C++ API looks very promising to use. My C++ is a bit rusty but I do believe that I will be able to find a way to do this when I actually sit down and focus for a few hours.

[Here](https://tesseract-ocr.github.io/tessdoc/Examples_C++.html), I have included a resource for where the Tesseract C++ is used in a variety of examples.

EDIT: djinni is not actively maintained, and is archived. We will need to look for alternatives to this if we would like to move forward with this.

**Comment by dyc3** [comment]
I have a feeling that we are going to encounter the same-ish problems that we were having getting mlkit and tesseract js to work. Mainly because we are still going to end up building native modules, and expo doesn't really like making that easy.

**Comment by aejester** [comment]
I looked into this, and I believe that as long as we can create the bindings for both platforms it should be fine. But I am not sure, as I have only looked into this approach for about an hour or 2.

**Comment by aejester** [comment]
This is a dead end.
