### ISSUE TITLE
Add splash page

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#35]
A splash page is a welcome page that is displayed when a user first open the apps. If you have ever used Tinder, think of the little fire icon that appears before the app proper loads. We should add a splash page that appears when the app first opens that contains the full-color version of the app logo.

I'll add an image of an example splash page in a comment below.

**Comment by carpenterd777** [comment]
![Screenshot_20210919-204311.png](https://user-images.githubusercontent.com/21251320/133948398-c9c751be-f9f4-48ae-9f8e-f2edc0746231.png)

Here is AnkiDroid's splash page. It appears very briefly before the main view of the app loads.

**Comment by dyc3** [comment]
IIRC, this is basically a metadata change. There's already a splash screen when the app starts, it just shows the wrong image.

**Comment by dyc3** [comment]
Actually, we might want to have this when loading the ML models https://docs.expo.dev/versions/v42.0.0/sdk/splash-screen/

**Comment by carpenterd777** [comment]
> 
> 
> Actually, we might want to have this when loading the ML models https://docs.expo.dev/versions/v42.0.0/sdk/splash-screen/

good idea, it figures that splash screens are also for loading but I did not think of that at first.
