### ISSUE TITLE
ML model transition from object analysis to character analysis

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#41]
Currently the model is generalized so that it detects objects from images. We only care about words, but that can be broken down into individual characters. Our next step with the model will be to use it exclusively for detecting characters.

**Comment by dyc3** [comment]
The model currently being used is not that general, and would not fall in line with other implementations I've seen. We should talk about this during the next GBM.

**Comment by carpenterd777** [comment]
No longer relevant since tesseract is used on the remote server, which is being used since #73.
