### ISSUE TITLE
Object detection is slow

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/monocle#42]
Currently, it takes ~30-40 seconds to get results after taking a picture.

The preprocessing (turning it into a tensor) takes a long time, and then loading the model takes a long time. These could probably be shortened or avoided.

**Comment by dyc3** [comment]
Specifically,

- `readAsStringAsync` is slow, somehow
- `base64ImageToTensor` is basically instant
- `cocoSsd.load()` is slow, and also destroys memory consumption if you take more than one picture

**Comment by carpenterd777** [comment]
Not sure if this is relevant anymore, since processing was moved on-server since #73.
