### ISSUE TITLE
Suffix `View` is potentially confusing

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#57]
The `View` suffix is currently intended for components that take up the entirety of the mobile device screen. However, React Native `View` components do not necessarily take up the entirety of the screen. This can cause confusion some may be lead to think that a full-size component will only take up some the screen, or that a full-screen component should not get the suffix `View`.

Let's move all of the `View` components into a folder called `/screens` and change the suffix of each component to `Screen`.

**Comment by aejester** [comment]
I am on board with this, but what if we called the folder `/views` for consistency?

**Comment by carpenterd777** [comment]
depend on what the suffix is I think. if we choose the suffix `View`, then yes we should go with `/views`. otherwise, if we choose the suffix `Screen`, then we should go with `/screens`.

**Comment by aejester** [comment]
Right.
