### ISSUE TITLE
Restructure folders to reflect split between server and front-end

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#67]
Now that this repo contains a server, it would be nice to restructure the directories so that there are two main sub-folders: `api-server` and `front-end`. This way it is clear what files directly relate to the server that runs remotely, and what files will change the user interface on the mobile app.

**Comment by dyc3** [comment]
For reference on best practice: https://docs.npmjs.com/cli/v7/using-npm/workspaces
