### ISSUE TITLE
Snap photo button component

### ISSUE THREAD

**Issue by carpenterd777** [StevensSEC/monocle#8]
A button will need to be added to the bottom of the camera view that stops the video feed and saves the last frame taken to be analyzed. This button should be round to mimic this feature on other popular camera apps.

**Comment by dyc3** [comment]
Hey do you think you could do this today? No styling, just the button.

**Comment by carpenterd777** [comment]
Yeah I should be able to. I've had this on low priority in case someone else wanted to give it a shot
